# Site settings
title: thienvinhmax.fun
email: max@richmanmax.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: /new-website-test # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor



